### ISSUE TITLE
#6 - Screenshot can be saved to the local forage DB

### ISSUE THREAD

**Issue by ajithkabraham** [saintograph/tag-it#10]
The plugin should be able to save a screenshot.

This feature will enable us to implement the following:

    User can take a screenshot of the active browser page
    Screenshot will be saved in local forage as a blob

Definition of Done:

    screenshot is saved in local forage as blob
    failing unit test passes
    extension works on Chrome and Firefox

**Comment by saintograph** [comment]
@ajithkabraham The naming convention of issues are `#no - feature`

**Comment by ajithkabraham** [comment]
> 
> 
> @ajithkabraham The naming convention of issues are `#no - feature`
Thanks Winfred. Will keep that in mind for the next.

**Comment by SimonH1821** [comment]
Appears to work as intended and the code looks good. 

Potentially add some more comments for the graders but other than that looks good. Found the screenshots saving correctly in the local forage. 

Also the button seems to be a bit close to the save link one so some CSS may be required?
