### ISSUE TITLE
#8 - Web page word count/parser

### ISSUE THREAD

**Issue by saintograph** [saintograph/tag-it#12]
This feature should implement the following:
* strip a web page of its tags
* count the number of words on a page, not including navigation links or button lables
* create a rough count of the number of words on a page based on tags (i.e. `<p>`, `<h1>` - `<h6>`)

**Comment by SimonH1821** [comment]
Works well and I see no issues with the code other than probably needing some comments for the graders as they seem to be a requirement in all assignments.

One key point in the Wiki or in the code is something to verify the reading time calculation such as a link to a paper that states the average words read per minute such as https://irisreading.com/what-is-the-average-reading-speed/
