### ISSUE TITLE
#3 - Links should be validated

### ISSUE THREAD

**Issue by saintograph** [saintograph/tag-it#4]
# Links should be validated

Every link should be validated for a valid web URL. An error message should be displayed to the user if an invalid URL is entered.

The regex validation function should be written separately as an utility function and placed in its own folder.

**Definition of Done:**
- validation function correctly identifies valid/invalid URLs
- unit tests for validation function written
- extension feature works on Chrome and Firefox

**Comment by anilganireddy** [comment]
Merged to develop.
